#!/usr/bin/env bash

if
  [[ -s "/home/coder/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment" ]]
then
  source "/home/coder/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/coder/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment'" >&2
  exit 1
fi
